# ¬°Aprendiendo Pandas! üêº

Repaso de lo aprendido sobre Python, e introduccion de la principal estructuras de datos de Pandas, los `DataFrames`. Estos son datos tabulares bidimensionales, de tama√±o variable y potencialmente heterog√©neos. La clase se dividir√° en los siguientes puntos:

1. Crearemos datos de prueba para nuestro proyecto.
2. Exploremos los datos creados.
3. ¬øC√≥mo podemos preparar un correo electr√≥nico?.
4. ¬°Reto!.

In [ ]:
# Instalamos una dependencia que no viene instalada en Colab por defecto
!pip install Faker

Collecting Faker
  Downloading Faker-13.2.0-py3-none-any.whl (1.5 MB)
     |‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà| 1.5 MB 15.6 MB/s
Requirement already satisfied: typing-extensions>=3.10.0.2 in /usr/local/lib/python3.7/dist-packages (from Faker) (3.10.0.2)
Requirement already satisfied: python-dateutil>=2.4 in /usr/local/lib/python3.7/dist-packages (from Faker) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.4->Faker) (1.15.0)
Installing collected packages: Faker
Successfully installed Faker-13.2.0

In [ ]:
# Importamos las dependencias
import pandas as pd # Manejo de datos
import numpy as np #¬†Estadistica
from datetime import datetime #¬†Formato de fechas
from faker import Faker # Generacion de datos de prueba

# 1 Crearemos datos de prueba para nuestro proyecto

In [ ]:
fake = Faker()
Faker.seed(4321) #¬†Si quieres que te salga lo mismo que a mi usa esta l√≠nea
N_SAMPLE = 1000 #¬†Numero de contactos a generar

In [ ]:
#¬†Generamos los datos utilizando una list comprehension
#¬†La estructura de datos resultante es una lista de listas

contact_list = [ [ fake.first_name(), fake.last_name(), fake.address(),
                   fake.free_email(), fake.company(), *fake.currency(), 
                   fake.date_time() ] for _ in range(N_SAMPLE) ]

In [ ]:
#¬†Convertimos la lista de listas a un pandas DataFrame con nombres de columnas
contact_df = pd.DataFrame(contact_list, columns=['first name', 'last name', 'address', 
                                                 'email', 'company', 'sel_currency_code', 
                                                 'sel_currency_label', 'start_datetime'])

In [ ]:
contact_df

     first name  last name  ...          sel_currency_label      start_datetime
0      Jonathan    Russell  ...            Hungarian forint 2021-01-02 06:26:04
1       Melissa      Baker  ...         Mauritanian ouguiya 2014-10-01 06:15:58
2    Jacqueline     Mathis  ...  Trinidad and Tobago dollar 2000-06-13 04:28:17
3        Robert       Kirk  ...              Nigerian naira 1987-10-14 05:35:59
4        Andrew     Dunlap  ...               Brunei dollar 1981-06-12 10:51:21
..          ...        ...  ...                         ...                 ...
995   Christina     Weaver  ...                Peruvian sol 2008-12-04 14:51:29
996     William    Sanchez  ...               Croatian kuna 2016-07-28 16:15:28
997     Kenneth  Contreras  ...             Philippine peso 2009-04-12 04:10:27
998       Scott      Chang  ...              Tongan pa ªanga 2010-07-04 16:48:59
999      Amanda    Garrett  ...          South African rand 1983-06-21 22:41:45

[1000 rows x 8 columns]

In [ ]:
#¬†Usamos numpy para asignar una prioridad aleatoria entre 1 a 5 en valores enteros a cada contacto
contact_df['priority'] = np.random.randint(low=1, high=5, size=N_SAMPLE)

In [ ]:
contact_df.head()

   first name last name  ...      start_datetime priority
0    Jonathan   Russell  ... 2021-01-02 06:26:04        3
1     Melissa     Baker  ... 2014-10-01 06:15:58        4
2  Jacqueline    Mathis  ... 2000-06-13 04:28:17        3
3      Robert      Kirk  ... 1987-10-14 05:35:59        3
4      Andrew    Dunlap  ... 1981-06-12 10:51:21        3

[5 rows x 9 columns]

In [ ]:
# Guardamos nuestra base de datos de prueba
contact_df.to_csv('marketing_campaing_contacts.csv', index=False)

#¬†2 Exploremos los datos creados

In [ ]:
# Leemos
contact_df = pd.read_csv('marketing_campaing_contacts.csv')

In [ ]:
contact_df.head()

   first name last name  ...       start_datetime priority
0    Jonathan   Russell  ...  2021-01-02 06:26:04        3
1     Melissa     Baker  ...  2014-10-01 06:15:58        4
2  Jacqueline    Mathis  ...  2000-06-13 04:28:17        3
3      Robert      Kirk  ...  1987-10-14 05:35:59        3
4      Andrew    Dunlap  ...  1981-06-12 10:51:21        3

[5 rows x 9 columns]

In [ ]:
contact_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   first name          1000 non-null   object
 1   last name           1000 non-null   object
 2   address             1000 non-null   object
 3   email               1000 non-null   object
 4   company             1000 non-null   object
 5   sel_currency_code   1000 non-null   object
 6   sel_currency_label  1000 non-null   object
 7   start_datetime      1000 non-null   object
 8   priority            1000 non-null   int64
dtypes: int64(1), object(8)
memory usage: 70.4+ KB

## 2.1 Filtremos a los contactos que tienen entre 1 y 5 a√±os registrados en nuestra base

In [ ]:
#¬†Convertimos la columna al tipo de dato correcto
contact_df['start_datetime'] = pd.to_datetime(contact_df['start_datetime'])

In [ ]:
datetime.today()

datetime.datetime(2022, 2, 23, 17, 11, 35, 989277)

In [ ]:
datetime.today() - pd.Timedelta(hours=1)

datetime.datetime(2022, 2, 23, 16, 11, 37, 472968)

In [ ]:
# Contactos registrados hace menos de 5 a√±os
filtro = contact_df['start_datetime'] > datetime.today() - pd.Timedelta(days=365*5)
contact_df[filtro]

      first name last name  ...      start_datetime priority
0       Jonathan   Russell  ... 2021-01-02 06:26:04        3
19        Daniel      Ross  ... 2017-10-31 17:59:16        3
24       Russell    Palmer  ... 2018-06-09 02:56:54        4
37         Jason     Brown  ... 2021-01-30 23:03:38        3
56   Christopher      Mack  ... 2020-09-16 01:39:55        2
..           ...       ...  ...                 ...      ...
982        Laura  Davidson  ... 2021-10-01 05:58:15        1
984      Gregory   Johnson  ... 2021-01-05 10:21:26        3
985        Patty     Reese  ... 2022-01-26 20:21:43        4
988    Stephanie      Chen  ... 2021-03-26 18:27:50        3
989        James    George  ... 2020-04-07 21:45:23        2

[91 rows x 9 columns]

In [ ]:
# Contactos registrados hace m√°s de 1 a√±o 
contact_df[contact_df['start_datetime'] < datetime.today() - pd.Timedelta(days=365)]

     first name  last name  ...      start_datetime priority
0      Jonathan    Russell  ... 2021-01-02 06:26:04        3
1       Melissa      Baker  ... 2014-10-01 06:15:58        4
2    Jacqueline     Mathis  ... 2000-06-13 04:28:17        3
3        Robert       Kirk  ... 1987-10-14 05:35:59        3
4        Andrew     Dunlap  ... 1981-06-12 10:51:21        3
..          ...        ...  ...                 ...      ...
995   Christina     Weaver  ... 2008-12-04 14:51:29        3
996     William    Sanchez  ... 2016-07-28 16:15:28        3
997     Kenneth  Contreras  ... 2009-04-12 04:10:27        4
998       Scott      Chang  ... 2010-07-04 16:48:59        1
999      Amanda    Garrett  ... 1983-06-21 22:41:45        1

[980 rows x 9 columns]

In [ ]:
# Asignamos los dos filtros combinados a un nuevo DataFrame
contact_dff = contact_df[(contact_df['start_datetime'] < datetime.today() - pd.Timedelta(days=365)) &  # Mayor de 1 a√±o 
                         (contact_df['start_datetime'] > datetime.today() - pd.Timedelta(days=365*5))] # Menor de 5 a√±os

In [ ]:
contact_dff.shape

(71, 9)

## 2.2 Filtremos a los contactos de prioridad mayor a 3

In [ ]:
# Asignamos el resultado del filtro de priorida al mismo DataFrame
contact_dff = contact_dff[contact_dff['priority'] >= 3]

In [ ]:
contact_dff.shape

(40, 9)

In [ ]:
contact_dff

    first name  last name  ...      start_datetime priority
0     Jonathan    Russell  ... 2021-01-02 06:26:04        3
19      Daniel       Ross  ... 2017-10-31 17:59:16        3
24     Russell     Palmer  ... 2018-06-09 02:56:54        4
37       Jason      Brown  ... 2021-01-30 23:03:38        3
69       James       Hill  ... 2019-12-22 06:12:47        4
124     Joshua    Mccarty  ... 2019-06-06 23:01:44        3
129     Joanna     Barker  ... 2021-01-22 03:17:12        3
140    Matthew      Lopez  ... 2018-04-09 19:20:17        4
188      Allen      Price  ... 2018-05-21 09:48:48        3
192      Emily    Fischer  ... 2017-07-03 20:43:08        3
195    Cameron      Brown  ... 2017-07-02 21:56:15        3
216      Jenna       Levy  ... 2020-10-21 06:09:41        4
219     Briana      Lynch  ... 2019-10-14 11:08:46        4
241     Martin   Martinez  ... 2020-05-29 19:31:15        3
283    Jeffrey     Garcia  ... 2020-03-12 16:09:21        3
306    Vincent      Smith  ... 2017-07-29 19:49:18        4
388     Sharon  Contreras  ... 2017-08-17 01:22:30        3
412        Ann     Brewer  ... 2018-12-10 22:15:12        3
422     Rachel      Smith  ... 2019-08-19 15:33:34        4
449    Kenneth      Davis  ... 2018-04-04 15:29:09        3
477      Maria     Castro  ... 2018-08-10 18:44:23        3
479      Tammy    Kennedy  ... 2018-01-10 04:38:23        4
500     Daniel     Hayden  ... 2018-06-27 04:33:02        4
507     Trevor    Maxwell  ... 2017-12-07 17:04:43        3
554  Christine     Harmon  ... 2019-01-11 05:03:07        3
557     Teresa      Jones  ... 2020-10-20 18:13:22        3
564   Patricia  Nicholson  ... 2020-02-08 05:52:43        3
595    Michael  Rodriguez  ... 2019-06-20 19:26:36        3
682       Dean   Buchanan  ... 2019-12-28 05:08:21        3
707     Taylor     Hoover  ... 2020-10-28 14:47:48        4
775    Deborah  Patterson  ... 2020-05-19 15:41:15        4
786       Jill      Gomez  ... 2020-09-09 21:30:13        3
818       Adam     Miller  ... 2019-04-05 15:11:39        4
828      Erica    Jackson  ... 2017-11-02 22:13:09        3
866     Gerald     Franco  ... 2020-01-21 02:45:48        3
921       Lori       Hall  ... 2019-08-28 11:19:11        3
931    Vanessa      Davis  ... 2020-12-26 08:49:41        3
960      Sarah      Johns  ... 2019-07-12 23:49:44        4
973        Lee   Erickson  ... 2019-12-19 21:37:11        4
984    Gregory    Johnson  ... 2021-01-05 10:21:26        3

[40 rows x 9 columns]

# 3 ¬øC√≥mo podemos preparar un correo electr√≥nico?

En Python existe un m√©todo llamado **interpolaci√≥n de texto**, esto permite colocar **placeholders** en un texto plantilla que ser√°n rellenados seg√∫n el valor de nuestras variables. Esto nos ayudar√° a construir correos electronicos personalizados.

In [ ]:
# Variables de ejemplo
first_name = 'Paolo'
last_name = 'Bejarano'
address = 'Avenida Salaverry 2520, Jesus Maria'
priority = '4'
company = 'Kurios'

##¬†3.1 Ejemplos de f-strings

### 3.3 f-strings de una sola l√≠nea 

```python

f" Var 1: {var1}, Var 2: {var2}"

" Var 1: {var1}, Var 2: {var2}".format(var1, var2)

" Var 1: {}, Var 2: {}".format(var1, var2)

f' '
```

In [ ]:
oneline = f"Hola {first_name} {last_name} ‚úåüèΩ, ¬°Te üëãüèΩ desde {company}! üöÄ"

In [ ]:
oneline

'Hola Paolo Bejarano ‚úåüèΩ, ¬°Te üëãüèΩ desde Kurios! üöÄ'

In [ ]:
print(oneline)

Hola Paolo Bejarano ‚úåüèΩ, ¬°Te üëãüèΩ desde Kurios! üöÄ

In [ ]:
oneline = f'Hola {first_name} {last_name} ‚úåüèΩ, ¬°Te üëãüèΩ desde {company}! üöÄ'

In [ ]:
print(oneline)

Hola Paolo Bejarano ‚úåüèΩ, ¬°Te üëãüèΩ desde Kurios! üöÄ

In [ ]:
oneline = f'Hola {first_name} {last_name} ‚úåüèΩ, ¬°Te "üëãüèΩ" desde {company}! üöÄ'

In [ ]:
print(oneline)

Hola Paolo Bejarano ‚úåüèΩ, ¬°Te "üëãüèΩ" desde Kurios! üöÄ

In [ ]:
oneline = f"Hola {first_name} {last_name} ‚úåüèΩ, ¬°Te 'üëãüèΩ' desde '{company}'! üöÄ"

In [ ]:
print(oneline)

Hola Paolo Bejarano ‚úåüèΩ, ¬°Te 'üëãüèΩ' desde 'Kurios'! üöÄ

### 3.3 f-strings de m√∫ltiples l√≠neas 

```python

f"""

Lista de variables:

- Var 1: {var1} 
- Var 2: {var2}

"""

```

In [ ]:
mail_template = f"""
Hola {first_name} üëãüèΩ 

En {company} estamos contentos de seguir trabajando con la familia {last_name} ü§ó.
Eres un cliente de {priority} üåü, eso te hace muy importante para nosotros.
Por ello queremos actualizar tu direcci√≥n para enviarte un üéÅ por tu preferencia.

\tüè° Direcci√≥n registrada: '{address}'

Muchas gracis por tu tiempo y atenci√≥n. Esperamos escuchar de t√≠ pronto ‚úåüèΩ
"""

In [ ]:
mail_template

"\nHola Paolo üëãüèΩ \n\nEn Kurios estamos contentos de seguir trabajando con la familia Bejarano ü§ó.\nEres un cliente de 4 üåü, eso te hace muy importante para nosotros.\nPor ello queremos actualizar tu direcci√≥n para enviarte un üéÅ por tu preferencia.\n\n\tüè° Direcci√≥n registrada: 'Avenida Salaverry 2520, Jesus Maria'\n\nMuchas gracis por tu tiempo y atenci√≥n. Esperamos escuchar de t√≠ pronto ‚úåüèΩ\n"

In [ ]:
print(mail_template)

Hola Paolo üëãüèΩ

En Kurios estamos contentos de seguir trabajando con la familia Bejarano ü§ó.
Eres un cliente de 4 üåü, eso te hace muy importante para nosotros.
Por ello queremos actualizar tu direcci√≥n para enviarte un üéÅ por tu preferencia.

	üè° Direcci√≥n registrada: 'Avenida Salaverry 2520, Jesus Maria'

Muchas gracis por tu tiempo y atenci√≥n. Esperamos escuchar de t√≠ pronto ‚úåüèΩ

<img src="https://i.gifer.com/origin/4c/4c8146590c298b7099c37335ec29e404_w200.gif" alt="drawing" width="600"/>

#¬†4 ¬°Reto! 

* Utilizando el √∫ltimo ejemplo realiza los cambios necesarios en el c√≥digo para que en lugar de indicar el n√∫mero de estrellas directamente agreguen/quiten emojis de estrella seg√∫n el valor de la variable `priority`

* Ejemplo de salida esperada:

```python
# Considerando
priority = 4
```

>Hola Claudio üëãüèΩ ...  
>
>Eres un cliente de üåüüåüüåüüåü, eso te hace muy importante para nosotros.
>
>... Muchas gracias por tu tiempo y atenci√≥n. Esperamos escuchar de t√≠ pronto ‚úåüèΩ

In [ ]:
###¬†Coloca tu c√≥digo aqu√≠



###